.TH "BigfootDS.BigfootNormalsInverter" 3 "Mon Aug 6 2018" "Version 1" "BigfootDS Unity Tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BigfootDS.BigfootNormalsInverter
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInvertMeshNormals\fP ()"
.br
.RI "Inverts the normals of a mesh as specified by the \fBBigfootNormalsInverter\fP component\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "MeshFilter \fBmeshToInvert\fP"
.br
.RI "The specified mesh that will have its normals inverted\&. The script will automatically fetch this component on the same object if this field is left blank\&. "
.ti -1c
.RI "bool \fBautoInverter\fP = true"
.br
.RI "If enabled, this will invert the normals of the desired mesh as soon as physically possible\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void BigfootDS\&.BigfootNormalsInverter\&.InvertMeshNormals ()"

.PP
Inverts the normals of a mesh as specified by the \fBBigfootNormalsInverter\fP component\&. 
.SH "Member Data Documentation"
.PP 
.SS "bool BigfootDS\&.BigfootNormalsInverter\&.autoInverter = true"

.PP
If enabled, this will invert the normals of the desired mesh as soon as physically possible\&. 
.SS "MeshFilter BigfootDS\&.BigfootNormalsInverter\&.meshToInvert"

.PP
The specified mesh that will have its normals inverted\&. The script will automatically fetch this component on the same object if this field is left blank\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for BigfootDS Unity Tools from the source code\&.
