.TH "BigfootDS.BigfootDummyTestScript" 3 "Mon Aug 6 2018" "Version 1" "BigfootDS Unity Tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BigfootDS.BigfootDummyTestScript \- Use this script to sandbox & test other scripts, functions and features\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDummyTestRollD20\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnumOfHeads\fP"
.br
.ti -1c
.RI "int \fBnumOfTails\fP"
.br
.ti -1c
.RI "List< string > \fBcoinFlipResults\fP = new List<string>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Use this script to sandbox & test other scripts, functions and features\&. 



.SH "Author"
.PP 
Generated automatically by Doxygen for BigfootDS Unity Tools from the source code\&.
