.TH "BigfootDS.BigfootWebColoursDefault" 3 "Mon Aug 6 2018" "Version 1" "BigfootDS Unity Tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BigfootDS.BigfootWebColoursDefault
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSingletonScriptableObject< BigfootWebColoursDefault >\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Material \fBAliceBlue\fP"
.br
.ti -1c
.RI "Material \fBAntiqueWhite\fP"
.br
.ti -1c
.RI "Material \fBAqua\fP"
.br
.ti -1c
.RI "Material \fBAquamarine\fP"
.br
.ti -1c
.RI "Material \fBAzure\fP"
.br
.ti -1c
.RI "Material \fBBeige\fP"
.br
.ti -1c
.RI "Material \fBBisque\fP"
.br
.ti -1c
.RI "Material \fBBlack\fP"
.br
.ti -1c
.RI "Material \fBBlanchedAlmond\fP"
.br
.ti -1c
.RI "Material \fBBlue\fP"
.br
.ti -1c
.RI "Material \fBBlueViolet\fP"
.br
.ti -1c
.RI "Material \fBBrown\fP"
.br
.ti -1c
.RI "Material \fBBurlyWood\fP"
.br
.ti -1c
.RI "Material \fBCadetBlue\fP"
.br
.ti -1c
.RI "Material \fBChartreuse\fP"
.br
.ti -1c
.RI "Material \fBChocolate\fP"
.br
.ti -1c
.RI "Material \fBCoral\fP"
.br
.ti -1c
.RI "Material \fBCornflowerBlue\fP"
.br
.ti -1c
.RI "Material \fBCornsilk\fP"
.br
.ti -1c
.RI "Material \fBCrimson\fP"
.br
.ti -1c
.RI "Material \fBCyan\fP"
.br
.ti -1c
.RI "Material \fBDarkBlue\fP"
.br
.ti -1c
.RI "Material \fBDarkCyan\fP"
.br
.ti -1c
.RI "Material \fBDarkGoldenRod\fP"
.br
.ti -1c
.RI "Material \fBDarkGray\fP"
.br
.ti -1c
.RI "Material \fBDarkGrey\fP"
.br
.ti -1c
.RI "Material \fBDarkGreen\fP"
.br
.ti -1c
.RI "Material \fBDarkKhaki\fP"
.br
.ti -1c
.RI "Material \fBDarkMagenta\fP"
.br
.ti -1c
.RI "Material \fBDarkOliveGreen\fP"
.br
.ti -1c
.RI "Material \fBDarkOrange\fP"
.br
.ti -1c
.RI "Material \fBDarkOrchid\fP"
.br
.ti -1c
.RI "Material \fBDarkRed\fP"
.br
.ti -1c
.RI "Material \fBDarkSalmon\fP"
.br
.ti -1c
.RI "Material \fBDarkSeaGreen\fP"
.br
.ti -1c
.RI "Material \fBDarkSlateBlue\fP"
.br
.ti -1c
.RI "Material \fBDarkSlateGray\fP"
.br
.ti -1c
.RI "Material \fBDarkSlateGrey\fP"
.br
.ti -1c
.RI "Material \fBDarkTurquoise\fP"
.br
.ti -1c
.RI "Material \fBDarkViolet\fP"
.br
.ti -1c
.RI "Material \fBDeepPink\fP"
.br
.ti -1c
.RI "Material \fBDeepSkyBlue\fP"
.br
.ti -1c
.RI "Material \fBDimGray\fP"
.br
.ti -1c
.RI "Material \fBDimGrey\fP"
.br
.ti -1c
.RI "Material \fBDodgerBlue\fP"
.br
.ti -1c
.RI "Material \fBFireBrick\fP"
.br
.ti -1c
.RI "Material \fBFloralWhite\fP"
.br
.ti -1c
.RI "Material \fBForestGreen\fP"
.br
.ti -1c
.RI "Material \fBFuchsia\fP"
.br
.ti -1c
.RI "Material \fBGainsboro\fP"
.br
.ti -1c
.RI "Material \fBGhostWhite\fP"
.br
.ti -1c
.RI "Material \fBGold\fP"
.br
.ti -1c
.RI "Material \fBGoldenRod\fP"
.br
.ti -1c
.RI "Material \fBGray\fP"
.br
.ti -1c
.RI "Material \fBGrey\fP"
.br
.ti -1c
.RI "Material \fBGreen\fP"
.br
.ti -1c
.RI "Material \fBGreenYellow\fP"
.br
.ti -1c
.RI "Material \fBHoneyDew\fP"
.br
.ti -1c
.RI "Material \fBHotPink\fP"
.br
.ti -1c
.RI "Material \fBIndianRed\fP"
.br
.ti -1c
.RI "Material \fBIndigo\fP"
.br
.ti -1c
.RI "Material \fBIvory\fP"
.br
.ti -1c
.RI "Material \fBKhaki\fP"
.br
.ti -1c
.RI "Material \fBLavender\fP"
.br
.ti -1c
.RI "Material \fBLavenderBlush\fP"
.br
.ti -1c
.RI "Material \fBLawnGreen\fP"
.br
.ti -1c
.RI "Material \fBLemonChiffon\fP"
.br
.ti -1c
.RI "Material \fBLightBlue\fP"
.br
.ti -1c
.RI "Material \fBLightCoral\fP"
.br
.ti -1c
.RI "Material \fBLightCyan\fP"
.br
.ti -1c
.RI "Material \fBLightGoldenRodYellow\fP"
.br
.ti -1c
.RI "Material \fBLightGray\fP"
.br
.ti -1c
.RI "Material \fBLightGrey\fP"
.br
.ti -1c
.RI "Material \fBLightGreen\fP"
.br
.ti -1c
.RI "Material \fBLightPink\fP"
.br
.ti -1c
.RI "Material \fBLightSalmon\fP"
.br
.ti -1c
.RI "Material \fBLightSeaGreen\fP"
.br
.ti -1c
.RI "Material \fBLightSkyBlue\fP"
.br
.ti -1c
.RI "Material \fBLightSlateGray\fP"
.br
.ti -1c
.RI "Material \fBLightSlateGrey\fP"
.br
.ti -1c
.RI "Material \fBLightSteelBlue\fP"
.br
.ti -1c
.RI "Material \fBLightYellow\fP"
.br
.ti -1c
.RI "Material \fBLime\fP"
.br
.ti -1c
.RI "Material \fBLimeGreen\fP"
.br
.ti -1c
.RI "Material \fBLinen\fP"
.br
.ti -1c
.RI "Material \fBMagenta\fP"
.br
.ti -1c
.RI "Material \fBMaroon\fP"
.br
.ti -1c
.RI "Material \fBMediumAquaMarine\fP"
.br
.ti -1c
.RI "Material \fBMediumBlue\fP"
.br
.ti -1c
.RI "Material \fBMediumOrchid\fP"
.br
.ti -1c
.RI "Material \fBMediumPurple\fP"
.br
.ti -1c
.RI "Material \fBMediumSeaGreen\fP"
.br
.ti -1c
.RI "Material \fBMediumSlateBlue\fP"
.br
.ti -1c
.RI "Material \fBMediumSpringGreen\fP"
.br
.ti -1c
.RI "Material \fBMediumTurquoise\fP"
.br
.ti -1c
.RI "Material \fBMediumVioletRed\fP"
.br
.ti -1c
.RI "Material \fBMidnightBlue\fP"
.br
.ti -1c
.RI "Material \fBMintCream\fP"
.br
.ti -1c
.RI "Material \fBMistyRose\fP"
.br
.ti -1c
.RI "Material \fBMoccasin\fP"
.br
.ti -1c
.RI "Material \fBNavajoWhite\fP"
.br
.ti -1c
.RI "Material \fBNavy\fP"
.br
.ti -1c
.RI "Material \fBOldLace\fP"
.br
.ti -1c
.RI "Material \fBOlive\fP"
.br
.ti -1c
.RI "Material \fBOliveDrab\fP"
.br
.ti -1c
.RI "Material \fBOrange\fP"
.br
.ti -1c
.RI "Material \fBOrangeRed\fP"
.br
.ti -1c
.RI "Material \fBOrchid\fP"
.br
.ti -1c
.RI "Material \fBPaleGoldenRod\fP"
.br
.ti -1c
.RI "Material \fBPaleGreen\fP"
.br
.ti -1c
.RI "Material \fBPaleTurquoise\fP"
.br
.ti -1c
.RI "Material \fBPaleVioletRed\fP"
.br
.ti -1c
.RI "Material \fBPapayaWhip\fP"
.br
.ti -1c
.RI "Material \fBPeachPuff\fP"
.br
.ti -1c
.RI "Material \fBPeru\fP"
.br
.ti -1c
.RI "Material \fBPink\fP"
.br
.ti -1c
.RI "Material \fBPlum\fP"
.br
.ti -1c
.RI "Material \fBPowderBlue\fP"
.br
.ti -1c
.RI "Material \fBPurple\fP"
.br
.ti -1c
.RI "Material \fBRebeccaPurple\fP"
.br
.ti -1c
.RI "Material \fBRed\fP"
.br
.ti -1c
.RI "Material \fBRosyBrown\fP"
.br
.ti -1c
.RI "Material \fBRoyalBlue\fP"
.br
.ti -1c
.RI "Material \fBSaddleBrown\fP"
.br
.ti -1c
.RI "Material \fBSalmon\fP"
.br
.ti -1c
.RI "Material \fBSandyBrown\fP"
.br
.ti -1c
.RI "Material \fBSeaGreen\fP"
.br
.ti -1c
.RI "Material \fBSeaShell\fP"
.br
.ti -1c
.RI "Material \fBSienna\fP"
.br
.ti -1c
.RI "Material \fBSilver\fP"
.br
.ti -1c
.RI "Material \fBSkyBlue\fP"
.br
.ti -1c
.RI "Material \fBSlateBlue\fP"
.br
.ti -1c
.RI "Material \fBSlateGray\fP"
.br
.ti -1c
.RI "Material \fBSlateGrey\fP"
.br
.ti -1c
.RI "Material \fBSnow\fP"
.br
.ti -1c
.RI "Material \fBSpringGreen\fP"
.br
.ti -1c
.RI "Material \fBSteelBlue\fP"
.br
.ti -1c
.RI "Material \fBTan\fP"
.br
.ti -1c
.RI "Material \fBTeal\fP"
.br
.ti -1c
.RI "Material \fBThistle\fP"
.br
.ti -1c
.RI "Material \fBTomato\fP"
.br
.ti -1c
.RI "Material \fBTurquoise\fP"
.br
.ti -1c
.RI "Material \fBViolet\fP"
.br
.ti -1c
.RI "Material \fBWheat\fP"
.br
.ti -1c
.RI "Material \fBWhite\fP"
.br
.ti -1c
.RI "Material \fBWhiteSmoke\fP"
.br
.ti -1c
.RI "Material \fBYellow\fP"
.br
.ti -1c
.RI "Material \fBYellowGreen\fP"
.br
.ti -1c
.RI "List< Material > \fBmaterialsDefault\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for BigfootDS Unity Tools from the source code\&.
