.TH "BigfootDS.SimplePointToPointMover" 3 "Mon Aug 6 2018" "Version 1" "BigfootDS Unity Tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BigfootDS.SimplePointToPointMover
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBdestinationStopDelay\fP = 1"
.br
.ti -1c
.RI "float \fBdestinationDistanceOffset\fP = 0\&.5f"
.br
.ti -1c
.RI "Transform [] \fBpointsToMoveBetween\fP"
.br
.ti -1c
.RI "float \fBmovementSpeed\fP = 5"
.br
.ti -1c
.RI "bool \fBisStopped\fP = false"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for BigfootDS Unity Tools from the source code\&.
