.TH "BigfootDS.FolderStructureWizard" 3 "Mon Aug 6 2018" "Version 1" "BigfootDS Unity Tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BigfootDS.FolderStructureWizard
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableWizard\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBfoldersPrefix\fP = ''"
.br
.ti -1c
.RI "string [] \fBcustomFoldersToGenerate\fP = new string[] { '__Sandbox', '_Demo', '_ImportedAssets', 'Animations', 'Audio', 'Fonts', 'Materials', 'Models', 'Prefabs', 'Plugins', 'ScriptableObjects', 'Scripts', 'Shaders', 'Sprites', 'Textures', 'Audio/SFX', 'Audio/Music', 'Scripts/Editor', 'Plugins/iOS', 'Plugins/Android' }"
.br
.ti -1c
.RI "string [] \fBbackupFoldersToGenerate\fP = new string[0]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for BigfootDS Unity Tools from the source code\&.
