.TH "BigfootDS.SceneBasicsGenerator" 3 "Mon Aug 6 2018" "Version 1" "BigfootDS Unity Tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BigfootDS.SceneBasicsGenerator
.SH SYNOPSIS
.br
.PP
.PP
Inherits EditorWindow\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBShowWindow\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBobjectsToSpawn\fP"
.br
.ti -1c
.RI "string \fBotsName\fP = 'New GameObject'"
.br
.ti -1c
.RI "Vector3 \fBotsPosition\fP"
.br
.ti -1c
.RI "Vector3 \fBotsRotation\fP"
.br
.ti -1c
.RI "Vector3 \fBotsScale\fP = Vector3\&.one"
.br
.ti -1c
.RI "bool \fBotsStatic\fP = false"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for BigfootDS Unity Tools from the source code\&.
