.TH "BigfootDS" 3 "Mon Aug 6 2018" "Version 1" "BigfootDS Unity Tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BigfootDS
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBigfootDiceAndCoins\fP"
.br
.RI "The Bigfoot 'Dice And Coins' class handles some quick-to-use functions for dice rolls and coin flips\&. Twenty-sided dice, D100s, coins, and even custom-sized dice are supported here\&. "
.ti -1c
.RI "class \fBBigfootDummyTestScript\fP"
.br
.RI "Use this script to sandbox & test other scripts, functions and features\&. "
.ti -1c
.RI "class \fBBigfootEventInvoker\fP"
.br
.ti -1c
.RI "class \fBBigfootGeneralLocationFinder\fP"
.br
.ti -1c
.RI "class \fBBigfootNormalsInverter\fP"
.br
.ti -1c
.RI "class \fBBigfootWebColoursDefault\fP"
.br
.ti -1c
.RI "class \fBBigfootWebColoursMatte\fP"
.br
.ti -1c
.RI "class \fBBigfootWebColoursMetallic\fP"
.br
.ti -1c
.RI "class \fBColourChangerTester\fP"
.br
.ti -1c
.RI "class \fBFolderStructureGenerator\fP"
.br
.ti -1c
.RI "class \fBFolderStructureWizard\fP"
.br
.ti -1c
.RI "class \fBSceneBasicsGenerator\fP"
.br
.ti -1c
.RI "class \fBSceneChanging\fP"
.br
.ti -1c
.RI "class \fBSimplePointToPointMover\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBColourType\fP { \fBDefault\fP, \fBMatte\fP, \fBMetallic\fP }"
.br
.RI "The main colour types of the built-in web colour materials\&. Should be Default, Matte and Metallic! "
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBBigfootDS\&.ColourType\fP\fC [strong]\fP"

.PP
The main colour types of the built-in web colour materials\&. Should be Default, Matte and Metallic! 
.SH "Author"
.PP 
Generated automatically by Doxygen for BigfootDS Unity Tools from the source code\&.
