.TH "SingletonScriptableObject< T >" 3 "Mon Aug 6 2018" "Version 1" "BigfootDS Unity Tools" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SingletonScriptableObject< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "static T \fBdata\fP\fC [get]\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for BigfootDS Unity Tools from the source code\&.
